version: '3.8'

services:
  simple_mcp:
    build: ./simple_mcp
    ports:
      - "8015:8015"
    restart: always

  api_agent:
    build: ./api_agent
    ports:
      - "4015:4015"
    restart: always
      