name: Deploy

on:
  workflow_run:
    workflows: [ "Build and Push Images" ]
    types: [ completed ]
    branches: [ "main" ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ai360.velkerr.ru
          username: ai360p2026s015
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker network create mcp_network || true

            docker stop juice_simple_mcp juice_agent_api || true
            docker rm juice_simple_mcp juice_agent_api || true

            docker pull ghcr.io/anotherbottleofjuice/agent_api/simple-mcp:latest
            docker run -d --name juice_simple_mcp \
              --network mcp_network \
              -p 8015:8000 \
              -e SIMPLE_MCP_TOKEN=abacaba \
              ghcr.io/anotherbottleofjuice/agent_api/simple-mcp:latest

            docker pull ghcr.io/anotherbottleofjuice/agent_api/agent-api:latest
            docker run -d --name juice_agent_api \
              --network mcp_network \
              -p 4015:8000 \
              -e DEFAULT_MCP_URL=http://juice_simple_mcp:8000/sse \
              -e DEFAULT_MCP_TOKEN=abacaba \
              ghcr.io/anotherbottleofjuice/agent_api/agent-api:latest